AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  todo-list-aws
  Application TODO-LIST with SAM format

# Parámetros
Parameters:
  Stage:
    Type: String
    Default: default
    AllowedValues:
      - default
      - staging
      - production
    Description: Enter staging or production. Default is default  

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        DYNAMODB_TABLE: !Ref TodosDynamoDbTable
        ENDPOINT_OVERRIDE: ""

Resources:
  
  CreateTodoFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Handler: create.create
      Runtime: python3.10
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TodosDynamoDbTable}"
      Events:
        Create:
          Type: Api
          Properties:
            Path: /todos
            Method: post

  ListTodosFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Handler: list.list
      Runtime: python3.10
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Scan
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TodosDynamoDbTable}"
      Events:
        List:
          Type: Api
          Properties:
            Path: /todos
            Method: get

  GetTodoFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Handler: get.get
      Runtime: python3.10
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TodosDynamoDbTable}"
      Events:
        Get:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: get

  UpdateTodoFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Handler: update.update
      Runtime: python3.10
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TodosDynamoDbTable}"
      Events:
        Update:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: put

  DeleteTodoFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Handler: delete.delete
      Runtime: python3.10
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TodosDynamoDbTable}"
      Events:
        Delete:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: delete
            
  TodosDynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Sub "${Stage}-TodosDynamoDbTable"
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  BaseUrlApi:
    Description: "Base URL of API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  CreateTodoApi:
    Description: "API Gateway endpoint URL for ${opt:stage} stage for Create TODO"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/todos/"
  ListTodosApi:
    Description: "API Gateway endpoint URL for ${opt:stage} stage for List TODO"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/todos"
  GetTodoApi:
    Description: "API Gateway endpoint URL for ${opt:stage} stage for Get TODO"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/todos/{id}"
  UpdateTodoApi:
    Description: "API Gateway endpoint URL for ${opt:stage} stage for Update TODO"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/todos/{id}"
  DeleteTodoApi:
    Description: "API Gateway endpoint URL for ${opt:stage} stage for Delete TODO"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/todos/{id}"
