AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  todo-list-aws
  Application TODO-LIST with SAM format

# Parameters
Parameters:
  Stage:
    Type: String
    Default: default
    AllowedValues:
      - default
      - staging
      - production
    Description: Enter staging or production. Default is default  

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        DYNAMODB_TABLE: !Ref TodosDynamoDbTable
        ENDPOINT_OVERRIDE: ""

Resources:
  
  CreateTodoFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Handler: create.create
      Runtime: python3.10
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:Scan
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TodosDynamoDbTable}"
      Events:
        Create:
          Type: Api
          Properties:
            Path
